# Generated by Django 6.1.1 on 2026-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'Uzcard / Humo'), ('visa', 'Visa / Mastercard'), ('cash', 'Naqd pul')], default='cash', max_length=20, verbose_name="To'lov turi"),
        ),
    ]
