import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar";
import MobileBottomMenu from "@/components/shared/MobileBottomMenu";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body className="min-h-full">
        <div className="custom-container flex flex-col">
          <Navbar />
          <main className="flex-1">{children}</main>
          {/* <MobileBottomMenu /> */}
        </div>
      </body>
    </html>
  );
}
