# Generated by Django 6.1.1 on 2026-09-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=255, verbose_name='Do‘kon nomi')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/', verbose_name='Do‘kon logotipi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
            ],
            options={
                'verbose_name': 'Do‘kon',
                'verbose_name_plural': 'Do‘konlar',
                'db_table': 'shops',
                'ordering': ['-created_at'],
            },
        ),
    ]
