# Generated by Django 6.1.1 on 2026-09-09 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('cash', 'Naqd pul (Yetkazilganda)')], max_length=50, verbose_name='To‘lov tizimi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='To‘lov summasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='To‘lov holati')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Tranzaksiya ID (Tizim kodi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
