# Generated by Django 6.1.1 on 2026-09-09 06:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', 'To‘langan'), ('processing', 'Jarayonda'), ('shipped', 'Yo‘lda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Umumiy summa')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('quantity', models.PositiveBigIntegerField(default=1, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotilgan narxi')),
            ],
            options={
                'verbose_name': 'Buyurtma tarkibi',
                'verbose_name_plural': 'Buyurtma tarkiblari',
                'db_table': 'order_item',
            },
        ),
    ]
