# Generated by Django 6.1.1 on 2026-09-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Mijoz'), ('seller', 'Sotuvchi'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
